spring.application.name=jobhunter

#config database

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/jobhunter
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true


#config jwt
hoangmelinh.jwt.base64-secret=i0G7qzm58+98q8XGsacL+WFXwG3WmjvqtAgLbaQsUYukvrtu6VN88MPk0l8RVtq+c4l2fOY3aRKsvBC5zKqgMg==

#expiration
hoangmelinh.jwt.access-token-validity-in-seconds=8640000
hoangmelinh.jwt.refresh-token-validity-in-seconds=8640000

#config upload file
###
# #default = 1MB
# spring.servlet.multipart.max-file-size=50MB  

# #default = 10 MB (form data)
# spring.servlet.multipart.max-request-size=50MB
###
#config pagination
spring.data.web.pageable.one-indexed-parameters=true

